language: node_js
node_js:
- '4.1'
before_script:
- npm install -g gulp
script: gulp test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: gjlaubenstein@gmail.com
  api_key:
    secure: H+xVaST2p4/I1GDGPVkM6Z6LERg+0OSWp8dGk0ZTvthqhPo56JjmTWcYb+Excd8MtbtBsmBYlnARWlkjh5474Zh+EMmu75szAM8lRoo6nsy7gwyQy9MAKsdxGF7nnj8V/laObXme6aEDl9PnpnH995UhSNdS6hqDZayggI0Bz14hrqJT0YPD73+NTyTxp9FHJlvuf755IwchpH6CZCn5l/sw5LN6m+OmdOFIHM5fNz2AKlksPdsf6L7dr3eTO2KsKiyrYZGHxj/frwQLwW7z2gCZToZzGaj7n2bmRRdYJ7XJfKfWwbNgEh+uKw7i+Kv6kpjsAd/iZ8xBdr0quQuvn1pdOANxA5qXpTVdg50TgL2RiMtvEiqgI5/jLum8dH6G7Gync/jITcjopxHUz1trOc29ZqVcrSFb413VJM8DUYHp8Xo9/eJIxFELVuS2fgFMR2GrpcrTjnBMjseU/ISw7cuHTWKbkU52Ej+BgWtsSOAGRuqik5nY53SYUpSpW4EkcjzCe1Izg8Ytv3EfIpaAJdtJU5iIwHHpuW0NRydRxy8Ua9oiPKgKL3FZalJvIDA6ZHFDPtppbDpxzhqZCzmHMrdcPbbWOcGAZgMnWadhWDJ7+QRa1lxjfwEem0P1STfPpS4IArNDTdFEXywy7oJfAKQJwEA1E7IbWmjzYBtlVfQ=
  on:
    tags: true
    repo: gjlaubenstein/basic-instagram-client
env:
  global:
    secure: z/bjgw2AooHq1FTi6jerxA+8aLDNlee7Bn9bRKWd0mv8ovfjMNd2rqTHV/T75y/kRckwhr2fJiYqEj2sCJLmN3Ia6pM19IR5mtLuTOmI+YSoN24ryQBoR2caLXsiNX7a6+++LRF+K8g6yUy6DWJUmKJv8gcNU+9N/JHOWeqfXIIWD8EM1sr8N+qixp+WQtSBqfs1ealisFokq3SYp/BkA9WBF4Z0BtfpcKBnSgnwCS/nqQnk3SFybT6UwBEd8EZi2EY2MMh08xJpctbk+J1Aqi5C+AlmJEHVGxaZTzrKCQ+zAp7NB8uQJonSUt/zZvdBLWh+tdL7NyWJolVmH6/NLD3jpAbQ4Jz8iEPhjwYPqtiAhgA45yE4sUGPkAeuF7jq9eTlIRTnjbmJC+24oT/YAewF4HykocwkwozC8ZvHI4d2TOCqt1drlWSD0WJhO48V8U6vz+eANsMyEkDPZUKIgdBfxqAEwcOxO4lnD/K0MKqNG/zl7+6L0TI4UCPrQ3h+P26plXXqtIPvpkgVKoij4dRtrObFrWX8BDacwHn0x0MjSonCgaSDhegVwcyEA7eLvY4pnMYmfdpKMHDn1AEg8ltJ710I3qsuLTAb4hsgf7tERmtCs0S3VIlyMKx5PgCjzlMojeVEwJ/qNs0cLbDYCoYwNAvv6Xh534B4NjY590E=
