language: node_js
node_js:
- '4.1'
before_script:
- npm install -g gulp
script: gulp test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: gjlaubenstein@gmail.com
  api_key:
    secure: H+xVaST2p4/I1GDGPVkM6Z6LERg+0OSWp8dGk0ZTvthqhPo56JjmTWcYb+Excd8MtbtBsmBYlnARWlkjh5474Zh+EMmu75szAM8lRoo6nsy7gwyQy9MAKsdxGF7nnj8V/laObXme6aEDl9PnpnH995UhSNdS6hqDZayggI0Bz14hrqJT0YPD73+NTyTxp9FHJlvuf755IwchpH6CZCn5l/sw5LN6m+OmdOFIHM5fNz2AKlksPdsf6L7dr3eTO2KsKiyrYZGHxj/frwQLwW7z2gCZToZzGaj7n2bmRRdYJ7XJfKfWwbNgEh+uKw7i+Kv6kpjsAd/iZ8xBdr0quQuvn1pdOANxA5qXpTVdg50TgL2RiMtvEiqgI5/jLum8dH6G7Gync/jITcjopxHUz1trOc29ZqVcrSFb413VJM8DUYHp8Xo9/eJIxFELVuS2fgFMR2GrpcrTjnBMjseU/ISw7cuHTWKbkU52Ej+BgWtsSOAGRuqik5nY53SYUpSpW4EkcjzCe1Izg8Ytv3EfIpaAJdtJU5iIwHHpuW0NRydRxy8Ua9oiPKgKL3FZalJvIDA6ZHFDPtppbDpxzhqZCzmHMrdcPbbWOcGAZgMnWadhWDJ7+QRa1lxjfwEem0P1STfPpS4IArNDTdFEXywy7oJfAKQJwEA1E7IbWmjzYBtlVfQ=
  on:
    tags: true
    repo: gjlaubenstein/basic-instagram-client
env:
  global:
    secure: JKCYEnatlQuX3TFVVJ7NJ/xYGK73lAqHnd6cryaaNHmnNuYzHC0VCK/oZjIepBkM4s+TdarcGI2GWSJPjzFCsAzbcPG/IglisyWDUiuB+WQxgy98kOC8X+axhAtq6zMBH/Gse9HA3LsmvyiUlfHcifr7cWturYwOIqyYYmXvtFtGjF1qNvWz/YpyRB9XIMTUzMV6H2SmBkw9j1WZRmB9USF3NcXyxym2OYKf6an1WwuYOOnMZDMUXfZBmLvwicGm5UV/bwbgdEakEMUTP3dHpzEenTaE7ubxVfDHCGsPCAacZ590Su5d75SgVZUwbgN4BDUsVVmFrj7NVJ70EyrxUq1scbVUQAKjAGi4bi92Phq85L5vwHmmoWonoAsdxwukIjOy6d2Ha2keaDVbF8w2Q67EHy11gnDHqxAZ/ZCdYcIe78+LNqqOog/77PAUw4hdZU6N4gzsf+aax9mBZRc9zaDOQVZvkCmt4vkSN5PwYVdE2tCQ1mhSayaG9u3Fe/8FffCZ6Cn9MpGP7Znk4dI8b3/puTdYkDsnWdfcELpiB7Dw9OtjH9z3MHwwrvsxaEt/v5ZotvfJR7yGiAUkA1sWzjKkNw2ovBoDB4frTFiFJX45BvK17uJMi+4ALT+Rg9G5UrpDcupd8aDZpTJRdYRTJJSKQ8ExMvE3Wf/VUJO5N0Q=
