language: node_js
node_js:
- '4.1'
before_script:
- npm install -g gulp
script: gulp test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: gjlaubenstein@gmail.com
  on:
    tags: true
    repo: gjlaubenstein/basic-instagram-client
  api_key:
    secure: vQmgSHXWVgA1TuhGh+K8Gpji3E3sUEWEl4aZEiWJt1SvMla/yHz1bbh3fFo+Lx/b+kpM5SbiWUICxYqQee6gKX3fjlxGUjdVT+rfY5rEhcu9+HZamopkaU8G73nkvv2jSBHKT5fwDRm3wxxugrcFxsEgS1FDjGc49HJCy3yVSDBpBdZXM4cLFCT3VJzHVsQPZMnImt8SKxwvwEsivP7zdQ1RGmijBsiBXeunZ4BESktJkt6effb2vpMmNr6BCk+sv8HsTaYSCwn1eUBSMyv+GH5P9YDK64+G+JBDem/glnMXJkSFONMk2aBq/oNTh3Yz38TeTugCnNO13aNlBtUGxa/Ztxpf5vw2Q+5rE5WLtl90qg7IvWzy3g5D/AF875LDq5IxyE1/z39laQmzGGFc6ZtRk2fZOBcC9zw9PgrXuk/CIrsMFNF1BEOk4u2M1xQiNgNLQSG/TGbgImPxP2pDFmNxTghbcgxsVudQgm1U3ptV9TagfhXOLqY0W74/fVaRULTOwyaefTxELzxGIinLCoA3mA5cX8WXe0vtv6jzhjr72K6+6EII/acusMGYCzCO/o/HTrOsCXxhM4Fl8kLPx21eoms0mmVehnZhtgrUVkvsWw063NkWyYGQV2rw4Z3/kAJ58B1Z5Qch5ni/i9NE/M5w+L8SD/utW3a6zvSxR90=
env:
  global:
    secure: z/bjgw2AooHq1FTi6jerxA+8aLDNlee7Bn9bRKWd0mv8ovfjMNd2rqTHV/T75y/kRckwhr2fJiYqEj2sCJLmN3Ia6pM19IR5mtLuTOmI+YSoN24ryQBoR2caLXsiNX7a6+++LRF+K8g6yUy6DWJUmKJv8gcNU+9N/JHOWeqfXIIWD8EM1sr8N+qixp+WQtSBqfs1ealisFokq3SYp/BkA9WBF4Z0BtfpcKBnSgnwCS/nqQnk3SFybT6UwBEd8EZi2EY2MMh08xJpctbk+J1Aqi5C+AlmJEHVGxaZTzrKCQ+zAp7NB8uQJonSUt/zZvdBLWh+tdL7NyWJolVmH6/NLD3jpAbQ4Jz8iEPhjwYPqtiAhgA45yE4sUGPkAeuF7jq9eTlIRTnjbmJC+24oT/YAewF4HykocwkwozC8ZvHI4d2TOCqt1drlWSD0WJhO48V8U6vz+eANsMyEkDPZUKIgdBfxqAEwcOxO4lnD/K0MKqNG/zl7+6L0TI4UCPrQ3h+P26plXXqtIPvpkgVKoij4dRtrObFrWX8BDacwHn0x0MjSonCgaSDhegVwcyEA7eLvY4pnMYmfdpKMHDn1AEg8ltJ710I3qsuLTAb4hsgf7tERmtCs0S3VIlyMKx5PgCjzlMojeVEwJ/qNs0cLbDYCoYwNAvv6Xh534B4NjY590E=
